name: pedrolino
version: 0.0.1
base: core18
summary: Bug reproducer
description: |
  Minimal reproducer of bug encountered while working on the
  MicroStack snap.
grade: stable
confinement: classic

environment:
  PATH: $SNAP/usr/bin:$PATH

apps:
  pedrolino:
    command: bin/pedrolino
  wrapper:
    command: bin/pedrolino.wrapper
  sh:
    command: bin/test.sh 
  printpath:
    command: bin/printpath
    environment:
      PATH: $SNAP/other-path:$PATH

parts:
  pedrolino:
    plugin: python
    python-version: python3
    source: src/
    override-build: |
      snapcraftctl build
      install -d -m 0755 $SNAPCRAFT_PART_INSTALL/bin
      install -m 0755 test.sh $SNAPCRAFT_PART_INSTALL/bin/test.sh
      install -m 0755 pedrolino.wrapper $SNAPCRAFT_PART_INSTALL/bin/pedrolino.wrapper
  printpath:
    plugin: make
    source: printpath/
    override-build: |
      install -d -m 0755 $SNAPCRAFT_PART_INSTALL/bin
      gcc main.c -o $SNAPCRAFT_PART_INSTALL/bin/printpath
